#!/usr/bin/env python3
"""Preserve the audited hand-coded question bank from an immutable Git ref."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

from pipeline_common import ROOT

GENERATED_FILES = (
    "data/generated/accepted_questions.jsonl",
    "data/generated/question_candidates.jsonl",
    "data/generated/rejected_questions.jsonl",
    "data/generated/generation_report.json",
    "data/generated/sentence_primary_questions.json",
    "reports/question_generation_report.md",
)


def git_output(ref: str, path: str) -> bytes:
    result = subprocess.run(
        ["git", "show", f"{ref}:{path}"],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout


def git_commit(ref: str) -> str:
    return subprocess.check_output(
        ["git", "rev-parse", f"{ref}^{{commit}}"],
        cwd=ROOT,
        text=True,
    ).strip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ref", default="pre-formal-remap-a1ed4bd")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "data/generated/legacy_handcoded_a1ed4bd",
    )
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    files = []
    for source_path in GENERATED_FILES:
        payload = git_output(args.ref, source_path)
        destination = args.output / Path(source_path).name
        if destination.exists() and destination.read_bytes() != payload:
            raise ValueError(f"refusing to overwrite differing {destination}")
        destination.write_bytes(payload)
        files.append(
            {
                "source_path": source_path,
                "path": destination.name,
                "bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest(),
                "records": (
                    payload.count(b"\n")
                    if destination.suffix in {".jsonl", ".md"}
                    else None
                ),
            }
        )
        print(f"Preserved {source_path} -> {destination.relative_to(ROOT)}")
    manifest = {
        "description": (
            "Audited legacy bank generated by hard-coded provisional heuristics; "
            "retained for evidence and old-versus-new comparison only."
        ),
        "source_ref": args.ref,
        "source_commit": git_commit(args.ref),
        "public_default": False,
        "files": files,
    }
    manifest_path = args.output / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {manifest_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
